name: DevSecOps

on: [push]

jobs:
  dependencyCheck:
    runs-on: ubuntu-latest
    name: dependency check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project with Maven
        run: mvn clean install
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env: 
          JAVA_HOME: /opt/jdk
        continue-on-error: true
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
      - name: Upload Test Result
        uses: actions/upload-artifact@master
        with: 
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
  slscan:
    runs-on: ubuntu-latest
    needs: dependencyCheck
    name: Perform SL Scan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - uses: ShiftLeftSecurity/scan-action@master
        with: 
          type: "credscan,java,depscan"
      - uses: actions/upload-artifact@master
        with:
          name: SLSCAN reports
          path: ${{ github.workspace }}/reports
  docker:
    runs-on: ubuntu-latest
    needs: slscan
    name: Push To Docker Hub
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project with Maven
        run: mvn clean install
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops:latest .
        - name: Push to Docker Hub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops:latest